Assignment for lesson 4
privisi/clojure-training-2024 pull request #3
Opened 2024-01-25 11:06 UTC by Boinciel

2024-01-27 16:26 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  (println "'Lorem ipsum.' - Dotor L."))
This is just printing a quote, you aren't getting anything back from it

2024-01-27 16:27 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +    (deref quote4 2000 "Timed out.")))
This is not getting quotes, it's printing quotes out.

2024-01-27 16:28 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +                             "mojeek.com"])
This should be a set

2024-01-27 16:29 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +\nExample search: `search :bing \"eggs\"`"
what is this \n stuff doing here

2024-01-27 16:29 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +
This is hard to read, please rewrite this

2024-01-27 16:33 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +(defn fetch-search-engine-url
fetch-search-engine-url indicates you are just getting a URL, while what is returned is not that

2024-01-27 16:33 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  "Converts the keyword of any of the search engines in the map to "
Incomplete docstring

2024-01-27 16:35 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  (extract-urls (fetch-search-engine-url engine query)))
this function shouldn't be doing search operations, it should just be getting the URLS from some sort of input

2024-01-27 16:35 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  (map first (partition-by identity (sort output))))
I would of thought you can just convert the collection into a set to remove duplicates, also what is "output:

2024-01-27 16:36 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  (filter #(keyword-checker filter-list %) coll))
What is happening here? Why are you trying to compare strings with keywords

2024-01-27 16:37 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  [bonzi-buddy nendoroid]
put args list in-line with fn

2024-01-27 16:39 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +
weird indenting
and should be indented as
`(and foo
         bar)`

2024-01-27 16:41 UTC, privisi requested changes
Changes requested with questions

2024-01-29 12:30 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +                             "mojeek.com"])
Understood, change made.

2024-01-29 12:31 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +\nExample search: `search :bing \"eggs\"`"
Originally for docstring formatting, but I realize now that you can just do two newlines and it does the same thing.

2024-01-29 12:31 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +(defn fetch-search-engine-url
Changed the name of the function to be more in line with what it does.

2024-01-29 12:31 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  "Converts the keyword of any of the search engines in the map to "
Fixed, thanks.

2024-01-29 12:33 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  (extract-urls (fetch-search-engine-url engine query)))
I agree that it would make more sense for the function to do that with its current name. I've renamed it so it's more clear what it does in the program.

2024-01-29 12:34 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  (map first (partition-by identity (sort output))))
Right, that's a better method, thank you.

2024-01-30 07:01 UTC, privisi requested changes
Changes requested

2024-01-30 07:01 UTC, privisi commented on src/assignments/PAUL_OMAKI/Advent2018/day-1.clj
> +         past-totals #{(first int-list)}]
The first total is actually 0

2024-01-30 07:01 UTC, privisi commented on src/assignments/PAUL_OMAKI/Advent2018/day-1.clj
> +          (catch NumberFormatException e
try read-string

2024-01-30 07:01 UTC, privisi commented on src/assignments/PAUL_OMAKI/Advent2018/day-1.clj
> +      (recur (rest int-list) (+ first-int total) (conj past-totals (+ first-int total))))))
this is flawed, no matter what happens in the when, it will call recur

2024-01-30 07:15 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +                     (fetch-and-extract-all-urls engine query))))))
this is what threading is used for

2024-01-30 07:16 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +    (deref quote4 2000 "Timed out.")))
This needs to return a collection of quotes

2024-01-30 07:16 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> + "'Lorem ipsum.' - Dotor L.")
This is where the random sleep needs to happen

2024-01-30 07:17 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment05.clj
> +       (str/split-lines)))
You shouldn't need this function at all, split lines from file shouldn't be slurping anything, you are hiding the fact that it needs to be slurped inside here

2024-01-30 07:18 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  (println "'Lorem ipsum.' - Dotor L."))
Fixed, now it returns one of several quotes.

2024-01-30 07:18 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +    (deref quote4 2000 "Timed out.")))
Fixed, now it returns all the quotes a vector.

2024-01-30 07:23 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  (filter #(keyword-checker filter-list %) coll))
Maybe keyword isn't the correct word here, I've renamed the function.

2024-01-30 07:24 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  [bonzi-buddy nendoroid]
Fixed.

2024-01-30 07:24 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +
Things should be in line now.

2024-01-30 07:27 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  (not-any? true? (map #(str/includes? string %) list)))
This is incredibly confusing, you can't compare strings and keywords.

2024-01-30 07:33 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +
Function names and indenting changed to make it easier to read.

2024-01-30 07:47 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/Advent2018/day-1.clj
> +          (catch NumberFormatException e
Thanks, used read-string instead.

2024-01-30 07:48 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/Advent2018/day-1.clj
> +      (recur (rest int-list) (+ first-int total) (conj past-totals (+ first-int total))))))
Noted, using an if instead.

2024-01-30 07:48 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +                     (fetch-and-extract-all-urls engine query))))))
Noted, threading applied.

2024-01-30 07:48 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +    (deref quote4 2000 "Timed out.")))
They should return the quotes as a collection now.

2024-01-30 07:58 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> + "'Lorem ipsum.' - Dotor L.")
Makes sense. The random sleep is functional now.

2024-01-30 07:59 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment05.clj
> +       (str/split-lines)))
Split lines from file doesn't technically need to exist, so I moved the offending slurp inside grep.

2024-01-30 08:00 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  (not-any? true? (map #(str/includes? string %) list)))
My mistake, I've rephrased it to be more representative of function.

2024-01-30 08:02 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +          (deref quote4 2000 "Timed out."))))
You didn't do the rest of the question
The futures should update an atom that refers to a total word count for all quotes. The function will take the number of quotes to download as an argument and return the atom’s final value. Keep in mind that you’ll need to ensure that all futures have finished before returning the atom’s final value. Here’s how you would call it and an example result:

(quote-word-count 5)
; => {"ochre" 8, "smoothie" 2}

2024-01-30 08:05 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/Advent2018/day-1.clj
> +         past-totals #{(first int-list)}]
Noted, set the first past-total to 0.

2024-01-30 09:36 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +          (deref quote4 2000 "Timed out."))))
The rest of this question is finished now.

2024-01-30 13:33 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment05.clj
> +       (str/split-lines)))
The results of slurp should be passed into split-lines. This function shouldn't be slurping anything, slurp is not a pure function.
This function should be pure, you shouldn't need a function called split-lines-from-file as it's doing 2 things - slurping and then doing a manipulation.
Slurp should be done by itself and then the results passed into split-lines separately, not encapsulated in a function

2024-01-30 13:36 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +           (deref quote4 2000 nil))))
If your function arities work correctly,
then in this arity instead of hard coding 4 quotes, can't you just call the 2nd arity with the args 4 within itself and return that?

2024-01-30 13:37 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  (vec (filter identity (get-quotes quantity))))
Why are you filtering identity, that does nothing at all?

2024-01-30 13:37 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +(defn quote-word-count [quantity]
docstring?

2024-01-30 13:56 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +  (vec (filter identity (get-quotes quantity))))
I'm filtering for identity specifically to filter out the nil values from the next step since they didn't get retrieved in time. I added an inline comment noting as such.

2024-01-30 13:57 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +           (deref quote4 2000 nil))))
Good point, no need to keep around the defunct code there.

2024-01-30 14:01 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment04.clj
> +(defn quote-word-count [quantity]
Added docstring.

2024-01-30 14:25 UTC, privisi approved these changes
Approved

2024-01-30 14:25 UTC, merged