Lesson 6 vending machine assignment
privisi/clojure-training-2024 pull request #4
Opened 2024-01-31 06:47 UTC by Boinciel

2024-01-31 12:01 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment06.clj
> +  {:state :start :coins []})
normally the comment is on a line below the def

2024-02-01 02:26 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment06.clj
> +     (if (< 0 (- (coin-value machine) (price-of-soda drink)))
neg?

2024-02-01 02:27 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment06.clj
> +         (println "Refunding " (- (coin-value machine) (price-of-soda drink)) " cents.")
repeated calculation, you can put this in a let

2024-02-01 02:28 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment06.clj
> +             machine))
weird indenting

2024-02-01 02:28 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment06.clj
> +  (let [machine  machine
why?

2024-02-01 02:28 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment06.clj
> +        drink    (:button-value event)]
just destructure?

2024-02-01 02:29 UTC, privisi requested changes
Changes requested

2024-02-01 04:44 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment06.clj
> +  {:state :start :coins []})
It should be in the correct place now.

2024-02-01 04:45 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment06.clj
> +     (if (< 0 (- (coin-value machine) (price-of-soda drink)))
It only triggers if the surplus is positive.

2024-02-01 04:45 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment06.clj
> +             machine))
Fixed, thanks.

2024-02-01 04:45 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment06.clj
> +  (let [machine  machine
Good point, removed.

2024-02-01 06:03 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment06.clj
> +     (if (< 0 (- (coin-value machine) (price-of-soda drink)))
there is a function called neg? which does what you want

2024-02-01 06:23 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment06.clj
> +         (println "Refunding " (- (coin-value machine) (price-of-soda drink)) " cents.")
Adjusted code for readability.

2024-02-01 06:23 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment06.clj
> +     (if (< 0 (- (coin-value machine) (price-of-soda drink)))
Ah, I see. Thanks for the heads up. Fixed.

2024-02-01 17:02 UTC, privisi approved these changes

2024-02-01 17:02 UTC, merged