Lesson 7 pipedrive assignment
privisi/clojure-training-2024 pull request #5
Opened 2024-02-13 09:21 UTC by Boinciel

2024-02-14 06:41 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment07.clj
> +               (:body))))
you don't put futures in this, if someone want's to use parallelization, they will call these functions with it elsewhere

2024-02-14 06:42 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment07.clj
> +                (str url)
url should already be a string?

2024-02-14 06:43 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment07.clj
> +     (let [url-addition (str "/" id-num "/")]
look into format

2024-02-14 06:48 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment07.clj
> +   :deals                (:closed_deals_count org)})
this is not clojurey, these should be in kebab case if used back in clojure

2024-02-14 06:54 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment07.clj
> +  (let [entity-future (fetch-data url id-num)]
Output entity data shouldn't be calling a fetch, it looks like what you are really trying to do is just format the data

2024-02-14 06:55 UTC, privisi requested changes
.

2024-02-14 12:31 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment07.clj
> +                (str url)
Yes, it is already a string so this is unneeded. Fixed.

2024-02-14 12:31 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment07.clj
> +               (:body))))
I have removed all futures and derefs, thanks.

2024-02-14 12:32 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment07.clj
> +     (let [url-addition (str "/" id-num "/")]
Done, this is a better way of doing this task.

2024-02-14 12:34 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment07.clj
> +  (let [entity-future (fetch-data url id-num)]
True, the output-data functions aren't even necessary. They are gone and the (get () :data) is now just part of the type-specific fetches since that's the actual information we want.

2024-02-14 12:35 UTC, Boinciel commented on src/assignments/PAUL_OMAKI/assignment07.clj
> +   :deals                (:closed_deals_count org)})
Fixed, now the keys in the returned maps are kebab case.

2024-02-16 06:43 UTC, privisi commented on src/assignments/PAUL_OMAKI/assignment07.clj
> +      {:error "Failed to transfer data." :details (:body response)})))
you should throw instead of returning a map

2024-02-16 06:45 UTC, privisi approved these changes

2024-02-16 06:45 UTC, merged